
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef AGGUIDE_H
#define AGGUIDE_H

#include "nxtype.h"
//#include "data.h"

/* Prototypes of function provided by object dictionnary */
//UNS32 Agguide_valueRangeTest (UNS8 typeValue, void * value);
//const indextable * Agguide_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
//extern CO_Data Agguide_Data;
extern INTEGER16 FrontHitchDistance;		/* Mapped at index 0x2000, subindex 0x00*/
extern INTEGER16 RearAxisHeight;		/* Mapped at index 0x2001, subindex 0x00*/
extern INTEGER16 WheelBase;		/* Mapped at index 0x2002, subindex 0x00*/
extern INTEGER16 HitchDistance;		/* Mapped at index 0x2003, subindex 0x00*/
extern INTEGER16 LeverArmX;		/* Mapped at index 0x2004, subindex 0x00*/
extern INTEGER16 LeverArmY;		/* Mapped at index 0x2005, subindex 0x00*/
extern INTEGER16 LeverArmZ;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 ValveMinVoltage;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 ValveMaxVoltage;		/* Mapped at index 0x2008, subindex 0x00*/
extern INTEGER16 ValveOffset;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 GainLearn;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 Swap;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER32 IntxTrackLimit;		/* Mapped at index 0x200C, subindex 0x00*/
extern INTEGER16 IntxTrackStart;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 IntegralSwitch;		/* Mapped at index 0x200E, subindex 0x00*/
extern INTEGER16 IntxHeadingStart;		/* Mapped at index 0x200F, subindex 0x00*/
extern INTEGER16 Left;		/* Mapped at index 0x2010, subindex 0x00*/
extern INTEGER16 Centre;		/* Mapped at index 0x2011, subindex 0x00*/
extern INTEGER16 Right;		/* Mapped at index 0x2012, subindex 0x00*/
extern INTEGER8 AngelReverse;		/* Mapped at index 0x2013, subindex 0x00*/
extern INTEGER16 RollOffset;		/* Mapped at index 0x2014, subindex 0x00*/
extern INTEGER8 ValveTransfer;		/* Mapped at index 0x2015, subindex 0x00*/
extern INTEGER16 XTrack;		/* Mapped at index 0x2016, subindex 0x00*/
extern INTEGER16 XHeading;		/* Mapped at index 0x2017, subindex 0x00*/
extern INTEGER16 Demand;		/* Mapped at index 0x2018, subindex 0x00*/
extern UNS8 CalibrateCmd;		/* Mapped at index 0x2019, subindex 0x00*/
extern UNS16 CalibratePhase;		/* Mapped at index 0x201A, subindex 0x00*/
extern INTEGER16 WheelAngleRaw;		/* Mapped at index 0x201B, subindex 0x00*/
extern INTEGER16 WheelAngle;		/* Mapped at index 0x201C, subindex 0x00*/
extern INTEGER16 Roll;		/* Mapped at index 0x201D, subindex 0x00*/
extern INTEGER16 Pitch;		/* Mapped at index 0x201E, subindex 0x00*/
extern INTEGER16 Yaw;		/* Mapped at index 0x201F, subindex 0x00*/
extern INTEGER32 Longitude;		/* Mapped at index 0x2020, subindex 0x00*/
extern INTEGER32 Latitude;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS16 Altitude;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS16 GPSHeading;		/* Mapped at index 0x2023, subindex 0x00*/
extern UNS8 Satellites;		/* Mapped at index 0x2024, subindex 0x00*/
extern UNS8 FixState;		/* Mapped at index 0x2025, subindex 0x00*/
extern INTEGER16 RollRaw;		/* Mapped at index 0x2026, subindex 0x00*/
extern INTEGER16 PitchRaw;		/* Mapped at index 0x2027, subindex 0x00*/
extern UNS8 SateliteChannel;		/* Mapped at index 0x2028, subindex 0x00*/
extern UNS16 DiagnoseCode;		/* Mapped at index 0x2029, subindex 0x00*/
extern UNS8 CANbusStatus;		/* Mapped at index 0x202A, subindex 0x00*/
extern REAL64 LineA;		/* Mapped at index 0x202B, subindex 0x00*/
extern REAL64 LineB;		/* Mapped at index 0x202C, subindex 0x00*/
extern REAL64 LineC;		/* Mapped at index 0x202D, subindex 0x00*/
extern UNS16 LineDirAngle;		/* Mapped at index 0x202E, subindex 0x00*/
extern UNS16 GpsPrecision;		/* Mapped at index 0x202F, subindex 0x00*/
extern UNS16 MachineSpeed;		/* Mapped at index 0x2030, subindex 0x00*/
extern UNS8 OEMType;		/* Mapped at index 0x2031, subindex 0x00*/
extern UNS8 GNSSMode;		/* Mapped at index 0x2032, subindex 0x00*/
extern UNS8 HighEndAngle;		/* Mapped at index 0x2033, subindex 0x00*/
extern UNS8 SmaplingFreq;		/* Mapped at index 0x2034, subindex 0x00*/
extern UNS16 HorizontalPrecision;		/* Mapped at index 0x2035, subindex 0x00*/
extern UNS16 VerticalPrecision;		/* Mapped at index 0x2036, subindex 0x00*/
extern UNS8 DropTime;		/* Mapped at index 0x2037, subindex 0x00*/
extern UNS8 SateliteType;		/* Mapped at index 0x2038, subindex 0x00*/
extern UNS8 DifferenceFormat;		/* Mapped at index 0x2039, subindex 0x00*/
extern UNS8 DifferenceMode;		/* Mapped at index 0x203A, subindex 0x00*/
extern UNS8 CommMode;		/* Mapped at index 0x203B, subindex 0x00*/
extern UNS8 CommFreq_1;		/* Mapped at index 0x203C, subindex 0x00*/
extern UNS32 CommFreq_2;		/* Mapped at index 0x203D, subindex 0x00*/
extern UNS64 LocalPos;		/* Mapped at index 0x203E, subindex 0x00*/
extern UNS8 Proportion;		/* Mapped at index 0x203F, subindex 0x00*/
extern UNS8 ValveHandle;		/* Mapped at index 0x2040, subindex 0x00*/
extern UNS8 AutoDrive;		/* Mapped at index 0x2041, subindex 0x00*/
extern UNS8 ParaSync;		/* Mapped at index 0x2042, subindex 0x00*/
extern UNS8 DriverStatus;		/* Mapped at index 0x2043, subindex 0x00*/
extern UNS16 RadioDelay;		/* Mapped at index 0x2044, subindex 0x00*/
extern UNS8 bReverse;		/* Mapped at index 0x2045, subindex 0x00*/
extern UNS16 UpdateDT;		/* Mapped at index 0x2046, subindex 0x00*/
extern INTEGER64 BASEPOS;		/* Mapped at index 0x2047, subindex 0x00*/
extern INTEGER64 SatelliteInfo;		/* Mapped at index 0x2048, subindex 0x00*/
extern INTEGER16 CaliLength;		/* Mapped at index 0x2049, subindex 0x00*/
extern INTEGER64 HardwareStatus;		/* Mapped at index 0x204A, subindex 0x00*/
extern INTEGER16 HeadingBias;		/* Mapped at index 0x204B, subindex 0x00*/
extern UNS32 Week;		/* Mapped at index 0x204C, subindex 0x00*/
extern UNS32 Second;		/* Mapped at index 0x204D, subindex 0x00*/
extern INTEGER16 VTGHeading;		/* Mapped at index 0x204E, subindex 0x00*/
extern INTEGER16 DualHeading;		/* Mapped at index 0x204F, subindex 0x00*/
extern REAL64 Gps_X;		/* Mapped at index 0x2050, subindex 0x00*/
extern REAL64 Gps_Y;		/* Mapped at index 0x2051, subindex 0x00*/
extern REAL64 Gps_Z;		/* Mapped at index 0x2052, subindex 0x00*/
extern INTEGER32 IMU_ax;		/* Mapped at index 0x2053, subindex 0x00*/
extern INTEGER32 IMU_ay;		/* Mapped at index 0x2054, subindex 0x00*/
extern INTEGER32 IMU_az;		/* Mapped at index 0x2055, subindex 0x00*/
extern INTEGER32 IMU_gx;		/* Mapped at index 0x2056, subindex 0x00*/
extern INTEGER32 IMU_gy;		/* Mapped at index 0x2057, subindex 0x00*/
extern INTEGER32 IMU_gz;		/* Mapped at index 0x2058, subindex 0x00*/
extern INTEGER32 IMU_hx;		/* Mapped at index 0x2059, subindex 0x00*/
extern INTEGER32 IMU_hy;		/* Mapped at index 0x205A, subindex 0x00*/
extern INTEGER32 IMU_hz;		/* Mapped at index 0x205B, subindex 0x00*/
extern INTEGER16 IMU_temperature;		/* Mapped at index 0x205C, subindex 0x00*/
extern UNS32 RegisterCode_1;		/* Mapped at index 0x205D, subindex 0x00*/
extern UNS32 RegisterCode_2;		/* Mapped at index 0x205E, subindex 0x00*/
extern UNS32 RegisterCode_3;		/* Mapped at index 0x205F, subindex 0x00*/
extern UNS32 RegisterEndTime;		/* Mapped at index 0x2060, subindex 0x00*/
extern UNS8 GpsPosZero;		/* Mapped at index 0x2061, subindex 0x00*/
extern UNS16 GpsSpeed;		/* Mapped at index 0x2062, subindex 0x00*/
extern UNS32 Gps_UTCTime;		/* Mapped at index 0x2063, subindex 0x00*/
extern UNS16 Gps_HDOP;		/* Mapped at index 0x2064, subindex 0x00*/
extern INTEGER32 Gps_EllipseHeight;		/* Mapped at index 0x2065, subindex 0x00*/
extern UNS8 bEnableWheelAutoCali;		/* Mapped at index 0x2066, subindex 0x00*/
extern UNS8 WheelNeutralAutoCalied;		/* Mapped at index 0x2067, subindex 0x00*/
extern INTEGER16 Plough_CenterOffset;		/* Mapped at index 0x2068, subindex 0x00*/
extern INTEGER16 Plough_GPSCenterDis;		/* Mapped at index 0x2069, subindex 0x00*/
extern UNS8 AllAttitude;		/* Mapped at index 0x206A, subindex 0x00*/
extern UNS16 HydraulicSersonValue;		/* Mapped at index 0x206B, subindex 0x00*/
extern UNS16 HydraulicThreshold;		/* Mapped at index 0x206C, subindex 0x00*/
extern UNS16 GainSteering;		/* Mapped at index 0x206D, subindex 0x00*/
extern UNS16 BetaAngle;		/* Mapped at index 0x206E, subindex 0x00*/
extern UNS8 AutoDeltaAndValveFlag;		/* Mapped at index 0x206F, subindex 0x00*/
extern UNS32 FireWareVersion;		/* Mapped at index 0x2070, subindex 0x00*/
extern UNS32 RegisterControlMachineCode;		/* Mapped at index 0x2071, subindex 0x00*/
extern UNS8 LineType;		/* Mapped at index 0x2072, subindex 0x00*/
extern UNS16 ValveAutoMinVoltage;		/* Mapped at index 0x2073, subindex 0x00*/
extern INTEGER16 ValveAutoOffset;		/* Mapped at index 0x2074, subindex 0x00*/
extern UNS8 SlopeCmd;		/* Mapped at index 0x2075, subindex 0x00*/
extern UNS16 GainxHeading;		/* Mapped at index 0x2076, subindex 0x00*/
extern UNS8 AutoCaliBack;		/* Mapped at index 0x2077, subindex 0x00*/
extern UNS8 AutoPWMStdLimit;		/* Mapped at index 0x2078, subindex 0x00*/
extern UNS16 GainPDPF;		/* Mapped at index 0x2079, subindex 0x00*/
extern UNS16 DeltaDeadZoon;		/* Mapped at index 0x207A, subindex 0x00*/
extern REAL64 An1;		/* Mapped at index 0x207B, subindex 0x00*/
extern UNS16 GainPDPB;		/* Mapped at index 0x207C, subindex 0x00*/
extern INTEGER32 AutoDeltaPara0;		/* Mapped at index 0x207D, subindex 0x00*/
extern INTEGER32 AutoDeltaPara1;		/* Mapped at index 0x207E, subindex 0x00*/
extern INTEGER32 AutoDeltaPara2;		/* Mapped at index 0x207F, subindex 0x00*/
extern UNS8 ExitNx200;		/* Mapped at index 0x2080, subindex 0x00*/
extern INTEGER32 AutoDeltaPara3;		/* Mapped at index 0x2081, subindex 0x00*/
extern INTEGER32 AutoDeltaParaMax;		/* Mapped at index 0x2082, subindex 0x00*/
extern INTEGER32 AutoPWML10;		/* Mapped at index 0x2083, subindex 0x00*/
extern INTEGER32 AutoPWML11;		/* Mapped at index 0x2084, subindex 0x00*/
extern INTEGER32 AutoPWML12;		/* Mapped at index 0x2085, subindex 0x00*/
extern INTEGER32 AutoPWML13;		/* Mapped at index 0x2086, subindex 0x00*/
extern INTEGER32 AutoPWML20;		/* Mapped at index 0x2087, subindex 0x00*/
extern INTEGER32 AutoPWML21;		/* Mapped at index 0x2088, subindex 0x00*/
extern INTEGER32 AutoPWML22;		/* Mapped at index 0x2089, subindex 0x00*/
extern INTEGER32 AutoPWML23;		/* Mapped at index 0x208A, subindex 0x00*/
extern INTEGER32 AutoPWMR10;		/* Mapped at index 0x208B, subindex 0x00*/
extern INTEGER32 AutoPWMR11;		/* Mapped at index 0x208C, subindex 0x00*/
extern INTEGER32 AutoPWMR12;		/* Mapped at index 0x208D, subindex 0x00*/
extern INTEGER32 AutoPWMR13;		/* Mapped at index 0x208E, subindex 0x00*/
extern INTEGER32 AutoPWMR20;		/* Mapped at index 0x208F, subindex 0x00*/
extern INTEGER32 AutoPWMR21;		/* Mapped at index 0x2090, subindex 0x00*/
extern INTEGER32 AutoPWMR22;		/* Mapped at index 0x2091, subindex 0x00*/
extern INTEGER32 AutoPWMR23;		/* Mapped at index 0x2092, subindex 0x00*/
extern INTEGER32 AutoPWMVminL;		/* Mapped at index 0x2093, subindex 0x00*/
extern INTEGER32 AutoPWMVminR;		/* Mapped at index 0x2094, subindex 0x00*/
extern INTEGER32 AutoPWMxRateMax;		/* Mapped at index 0x2095, subindex 0x00*/
extern INTEGER32 AutoPWMPidErrMax;		/* Mapped at index 0x2096, subindex 0x00*/
extern INTEGER32 AutoPWMPidErrAver;		/* Mapped at index 0x2097, subindex 0x00*/
extern INTEGER32 AutoPWMPidErrStd;		/* Mapped at index 0x2098, subindex 0x00*/
extern REAL64 Bn1;		/* Mapped at index 0x2099, subindex 0x00*/
extern REAL64 Cn1;		/* Mapped at index 0x209A, subindex 0x00*/
extern REAL64 Dn1;		/* Mapped at index 0x209B, subindex 0x00*/
extern REAL64 An2;		/* Mapped at index 0x209C, subindex 0x00*/
extern REAL64 Bn2;		/* Mapped at index 0x209D, subindex 0x00*/
extern REAL64 Cn2;		/* Mapped at index 0x209E, subindex 0x00*/
extern REAL64 Dn2;		/* Mapped at index 0x209F, subindex 0x00*/
extern REAL64 Ae1;		/* Mapped at index 0x20A0, subindex 0x00*/
extern REAL64 Be1;		/* Mapped at index 0x20A1, subindex 0x00*/
extern REAL64 Ce1;		/* Mapped at index 0x20A2, subindex 0x00*/
extern REAL64 De1;		/* Mapped at index 0x20A3, subindex 0x00*/
extern REAL64 Ae2;		/* Mapped at index 0x20A4, subindex 0x00*/
extern REAL64 Be2;		/* Mapped at index 0x20A5, subindex 0x00*/
extern REAL64 Ce2;		/* Mapped at index 0x20A6, subindex 0x00*/
extern REAL64 De2;		/* Mapped at index 0x20A7, subindex 0x00*/
extern REAL32 sk1;		/* Mapped at index 0x20A8, subindex 0x00*/
extern REAL32 sk2;		/* Mapped at index 0x20A9, subindex 0x00*/
extern REAL32 sk3;		/* Mapped at index 0x20AA, subindex 0x00*/
extern UNS8 AngleSensorType;		/* Mapped at index 0x20AB, subindex 0x00*/
extern UNS8 CardThroughSwitch;		/* Mapped at index 0x20AC, subindex 0x00*/
extern UNS16 RadioSignalStrength;		/* Mapped at index 0x20AD, subindex 0x00*/
extern INTEGER32 BaseCecfX;		/* Mapped at index 0x20AE, subindex 0x00*/
extern INTEGER32 BaseCecfY;		/* Mapped at index 0x20AF, subindex 0x00*/
extern INTEGER32 BaseCecfZ;		/* Mapped at index 0x20B0, subindex 0x00*/
extern INTEGER16 WBase;		/* Mapped at index 0x20B1, subindex 0x00*/
extern INTEGER16 PitchOffset;		/* Mapped at index 0x20B2, subindex 0x00*/
extern UNS16 GainxTrack;		/* Mapped at index 0x20B3, subindex 0x00*/
extern UNS16 GainR;		/* Mapped at index 0x20B4, subindex 0x00*/
extern UNS16 PTime;		/* Mapped at index 0x20B5, subindex 0x00*/
extern UNS16 PTimeOff;		/* Mapped at index 0x20B6, subindex 0x00*/
extern INTEGER16 OnlineAggresiveness;		/* Mapped at index 0x20B7, subindex 0x00*/
extern INTEGER16 ApproachAggresiveness;		/* Mapped at index 0x20B8, subindex 0x00*/
extern INTEGER16 MaxSteeringAngle;		/* Mapped at index 0x20B9, subindex 0x00*/
extern UNS8 ControlType;		/* Mapped at index 0x20BA, subindex 0x00*/
extern UNS8 CailFeedBack;		/* Mapped at index 0x20BB, subindex 0x00*/
extern UNS8 RangeData;		/* Mapped at index 0x20BC, subindex 0x00*/
extern UNS8 Sensitivity;		/* Mapped at index 0x20BD, subindex 0x00*/
extern UNS8 WheelMode;		/* Mapped at index 0x20BE, subindex 0x00*/
extern INTEGER16 MotorRatio;		/* Mapped at index 0x20BF, subindex 0x00*/
extern INTEGER16 MotorRatioShift;		/* Mapped at index 0x20C0, subindex 0x00*/
extern UNS16 MotorDeadCnt;		/* Mapped at index 0x20C1, subindex 0x00*/
extern INTEGER16 MotorDeadCntShift;		/* Mapped at index 0x20C2, subindex 0x00*/
extern UNS16 MotorMoment;		/* Mapped at index 0x20C3, subindex 0x00*/
extern UNS16 MotorKey1;		/* Mapped at index 0x20C4, subindex 0x00*/
extern UNS16 MotorKey2;		/* Mapped at index 0x20C5, subindex 0x00*/
extern UNS32 MotorParam1;		/* Mapped at index 0x20C6, subindex 0x00*/
extern UNS32 MotorParam2;		/* Mapped at index 0x20C7, subindex 0x00*/
extern UNS16 CalibrateEnableCmd;		/* Mapped at index 0x20C8, subindex 0x00*/
extern INTEGER16 VehicleFrontAxis;		/* Mapped at index 0x20C9, subindex 0x00*/
extern UNS8 GasensorInstallSite;		/* Mapped at index 0x20CA, subindex 0x00*/
extern UNS8 GasensorInstallDir;		/* Mapped at index 0x20CB, subindex 0x00*/
extern UNS8 GasensorSpeedLevel;		/* Mapped at index 0x20CC, subindex 0x00*/
extern UNS16 GasensorStaticAdjustment;		/* Mapped at index 0x20CD, subindex 0x00*/
extern UNS16 GasensorCondThreshold;		/* Mapped at index 0x20CE, subindex 0x00*/
extern UNS32 MotorT1;		/* Mapped at index 0x20CF, subindex 0x00*/
extern UNS32 MotorT2;		/* Mapped at index 0x20D0, subindex 0x00*/
extern UNS8 RadioType;		/* Mapped at index 0x20D1, subindex 0x00*/
extern UNS8 RadioProtocolType;		/* Mapped at index 0x20D2, subindex 0x00*/
extern UNS8 WifiSwitch;		/* Mapped at index 0x20D3, subindex 0x00*/
extern UNS16 GaSensorRaw;		/* Mapped at index 0x20D4, subindex 0x00*/
extern UNS8 WifiFeedback;		/* Mapped at index 0x20D5, subindex 0x00*/
extern UNS8 MotorType;		/* Mapped at index 0x20D6, subindex 0x00*/
extern UNS8 MotorControlType;		/* Mapped at index 0x20D7, subindex 0x00*/
extern UNS16 GainPDD;		/* Mapped at index 0x20D8, subindex 0x00*/
extern UNS8 ValveHzSwitch;		/* Mapped at index 0x20D9, subindex 0x00*/
extern UNS8 HeadingFloatEnable;		/* Mapped at index 0x20DA, subindex 0x00*/
extern UNS8 VehicleSpeedMin;		/* Mapped at index 0x20DB, subindex 0x00*/
extern UNS16 ControllerSerial;		/* Mapped at index 0x20DC, subindex 0x00*/
extern UNS8 GnssBack;		/* Mapped at index 0x20DD, subindex 0x00*/
extern UNS8 LonLatFlag;		/* Mapped at index 0x20DE, subindex 0x00*/
extern UNS16 GnssStationID;		/* Mapped at index 0x20DF, subindex 0x00*/
extern UNS16 MagneticNorthHeading;		/* Mapped at index 0x20E0, subindex 0x00*/
extern UNS8 VTGModeIndication;		/* Mapped at index 0x20E1, subindex 0x00*/
extern INTEGER32 MotorOverCurrent;		/* Mapped at index 0x20E2, subindex 0x00*/
extern UNS8 MotorOverloadTime;		/* Mapped at index 0x20E3, subindex 0x00*/
extern UNS8 FeedbackType;		/* Mapped at index 0x20E4, subindex 0x00*/
extern INTEGER16 CtrlU;		/* Mapped at index 0x20E5, subindex 0x00*/
extern INTEGER16 WheelAnglePDErr;		/* Mapped at index 0x20E6, subindex 0x00*/
extern INTEGER16 WasBias;		/* Mapped at index 0x20E7, subindex 0x00*/
extern INTEGER16 YawBias;		/* Mapped at index 0x20E8, subindex 0x00*/
extern UNS8 VehicleType;		/* Mapped at index 0x20E9, subindex 0x00*/
extern UNS8 RadioStep;		/* Mapped at index 0x20EA, subindex 0x00*/
extern UNS8 RadioAirBaudrate;		/* Mapped at index 0x20EB, subindex 0x00*/
extern UNS8 RadioPower;		/* Mapped at index 0x20EC, subindex 0x00*/
extern UNS8 PdoCheckCode;		/* Mapped at index 0x20ED, subindex 0x00*/
extern UNS8 GNSSNums;		/* Mapped at index 0x20EE, subindex 0x00*/
extern UNS8 UpdateFlag;		/* Mapped at index 0x20EF, subindex 0x00*/
extern UNS8 CardRegisterMode;		/* Mapped at index 0x20F0, subindex 0x00*/
extern UNS8 ElecControlStatus;		/* Mapped at index 0x20F1, subindex 0x00*/
extern UNS8 ElecControl;		/* Mapped at index 0x20F2, subindex 0x00*/
extern UNS8 ControlParasCheck;		/* Mapped at index 0x20F3, subindex 0x00*/
extern UNS8 HeadingSwap;		/* Mapped at index 0x20F4, subindex 0x00*/
extern UNS32 MotorVersion;		/* Mapped at index 0x20F5, subindex 0x00*/
extern UNS8 LogSwitch;		/* Mapped at index 0x20F6, subindex 0x00*/
extern UNS16 MotorVoltage;		/* Mapped at index 0x20F7, subindex 0x00*/
extern UNS16 MotorCurrentGainP;		/* Mapped at index 0x20F8, subindex 0x00*/
extern UNS16 MotorCurrentGainI;		/* Mapped at index 0x20F9, subindex 0x00*/
extern UNS8 CommunicationSwitch;		/* Mapped at index 0x20FA, subindex 0x00*/
extern UNS8 GainStraightness;		/* Mapped at index 0x20FB, subindex 0x00*/
extern REAL64 PureTrackU;		/* Mapped at index 0x20FC, subindex 0x00*/
extern UNS8 VoltageOutputFlag;		/* Mapped at index 0x20FD, subindex 0x00*/
extern UNS8 CalibrationCheck;		/* Mapped at index 0x20FE, subindex 0x00*/
extern UNS16 GNSSPosErrPara;
extern UNS8 GaSensorIndex;		/* Mapped at index 0x2102, subindex 0x00*/
extern UNS8 GaSensorType;		/* Mapped at index 0x2103, subindex 0x00*/
extern UNS8 AutoKeyEn;    /* Mapped at index 0xXXXX, subindex 0x00 */
extern UNS8 VehicleTransplanter;
extern UNS8 controllertype;//默认0: X10, 1:A100
extern INTEGER32 ZeroBaseCecfX;		/* 实时上报零点基准坐标X */
extern INTEGER32 ZeroBaseCecfY;		/* 实时上报零点基准坐标Y */
extern INTEGER32 ZeroBaseCecfZ;		/* 实时上报零点基准坐标Z */
extern UNS32 MotorTimeout;		/* 电机通讯异常时间判断, ms */
extern UNS8 AntiNums;/*,天线个数，1：单天线，2：双天线，默认1*/
extern UNS8 MotorKeyDisable;//电机按键功能设置，0:开启，1：禁用
extern UNS16 VehicleTypeReady; /* ready 车型类型*/
extern UNS8 HeadingInitSwitch; /* 航向初始化开关:  初始化条件严格:1； 初始化条件宽松:0*/
extern UNS8 GnssState;//0未开启融合返回0 1rtk 2 HPPP 3 EPPP 4 CHCPPP
extern UNS8 GnssSwitch;// 0:融合关闭  1:RTK+HPPP 2: RTK + E-PPP 3: RTK + CHCPPP
extern UNS8 LowSpeedModeButton;//低速模式开关 1:启用  2:关
extern UNS16 PlcVersion;	//PLC 版本号 1.2.3 = 291
extern INTEGER16 SteeringWheelPosition;	// 方向盘位置，精度1度；系统重启默认0度
extern UNS8 NmeaCorrectButton;//nmea 语句数据进行IMU修正开关  0:关  1:开
extern UNS8 NavWorkMode;//默认值0---自动驾驶 1---------引导模式（不提示方向盘异常）2---------自动驾驶模式（方向盘、电磁阀、CANBUS）3---------带方向盘的演示模式（展会用）4---------不带方向盘的演示模式（用户通过手滑改变方向）5---------卫星平地模式
extern UNS8 NoIMUMode;//默认值0--- 关闭无IMU模式（含有imu） 1--- 打开无IMU模式（不含imu）
extern UNS8 MotorLED;  // 电机LED亮度，范围1-20，默认20
extern UNS32 MotorSN1To4;  // SN 1-8位
extern UNS32 MotorSN5To8;
extern UNS32 MotorSN9To12;  // SN 9-12位
extern INTEGER16 PadMaxSteeringWheelProp;//-100~100,-MaxWheelAngle~MaxWheelAngle
extern UNS8 LovolSprayerTurnMode; //雷沃喷雾器转向模式 默认值为0      其他:1两轮  2四轮  3蟹行  18FFC2F0
extern UNS8 VisionConfidence; //视觉置信度
extern INTEGER64 HardwareStatus2;//视觉对行故障码
extern UNS8 CutOffCanhubFlag;//0使用 1禁用
extern UNS8 ImpMountPoint;/*,农具挂载位置，默认值0,  1：后挂载，2：前挂载，3：前后都挂载 */
extern INTEGER16 HitchDistance_FrontMount;		/*前挂载农具时，农具到前轮轴的距离*/
extern REAL64 Front_Longitude; /*前挂载农具时，农具经度*/
extern REAL64 Front_Latitude; /*前挂载农具时，农具纬度*/
extern REAL64 Local_X_receiver;                //接收机局部坐标 X
extern REAL64 Local_Y_receiver;            //接收机局部坐标 Y
extern REAL64 Local_Heading_receiver;   //接收机航向
extern INTEGER16 TargetWheelAngle;//目标前轮转角，分辨率0.01度
extern INTEGER16 CtrlHeadingBias;//控制库中计算的headingBias，分辨率0.01度
extern INTEGER16 Omiga;//车身转速，分辨率0.01度/秒

extern REAL64 MotorCurrent; // 电机电流，单位A
extern REAL64 TargetMotorSpeed; // 目标电机转速，单位degree/s
extern REAL64 MotorCurrentSpeed;  // 电机实际转速，单位degree/s
extern UNS8 AILabelOne;  // 数据标签1,直线度类型 0=没有标签
extern UNS8 AILabelTwo;  // 数据标签2, 场景类型 0=没有标签
extern UNS8 VisionGuideEnable; // 视觉导航开启标志，默认0，1=开启
extern REAL64 CtrlUploadPathCurvature;//控制上传的路径曲率，1/m
extern REAL64    CtrlPointE;//控制点ENU坐标下的E,m
extern REAL64    CtrlPointN;//制点ENU坐标下的N,m
extern REAL64    CtrlPointU;//控制点ENU坐标下的U,m
extern REAL64    CtrlPointLongitude;//控制点经度,rad
extern REAL64    CtrlPointLatitude;//控制点纬度,rad
extern REAL64    CtrlPointAltitude;//控制点高度,m
extern UNS8      StraightnessEnhance;//直线度增强，开（1），关（0）
extern UNS8      InterRowSpacingEnhance;//交接行增强，开（1），关（0）
extern REAL64 Coordinate_transformation_E_Offset; /*天宝导航线导入引起的E坐标偏移量  m */
extern REAL64 Coordinate_transformation_N_Offset; /*天宝导航线导入引起的N坐标偏移量  m */
extern REAL64 Coordinate_transformation_U_Offset; /*天宝导航线导入引起的U坐标偏移量  m */
extern REAL64 cloud_xTrack;//精度0.01，单位m
extern REAL64 cloud_xHeading;//精度0.01，单位度
extern REAL64 cloud_Longitude;//精度0.01
extern REAL64 cloud_Latitude;//精度0.01
extern UNS8 AI_tune; //AI调参开关，0：关闭，1：开启




#endif // AGGUIDE_H
